








scrape_configs:
  - job_name: stellar-lending-exporter-testnet
    metrics_path: /metrics
    static_configs:
      - targets: ['lending-exporter-testnet:9110']
        labels:
          network: testnet
